/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'G030_T12+G030T12' 
 * Target:  'G030T12' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g0xx.h"

/* Keil::Compiler&ARM Compiler:I/O:STDOUT&User@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
          #define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */


#endif /* RTE_COMPONENTS_H */
